name: Thank and Encourage Contributors

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  thank-and-encourage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine PR or issue
        id: pr-or-issue
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "::set-output name=type::PR"
          else
            echo "::set-output name=type::issue"
          fi

      - name: Comment on PR or issue
        id: comment
        run: |
          message=":tada: Thank you for opening this ${{ steps.pr-or-issue.outputs.type }}! Your contribution is greatly appreciated. :rocket:\n\nKeep up the good work, and don't hesitate to open more! Let's make this project even better together. :muscle:"
          echo "$message" > message.txt

      - name: Post comment
        uses: actions/github-script@0.10.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = require('fs').readFileSync('message.txt', 'utf-8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
